FROM tensorflow/tensorflow:2.15.0-gpu

USER root
RUN mkdir /serving
ADD docker/app/ /serving/app 
RUN mkdir -p /serving/app/bin
COPY  src/gpt/bin/gpt-books.keras /serving/app/lib
COPY  src/gpt/config/data.yaml /serving/app/config
COPY  src/gpt/config/vocab.json /serving/app/config
COPY  src/gpt/lib/token_and_position_embedding.py /serving/app/lib
COPY  src/gpt/gpt.py /serving/app/lib
COPY  src/gpt/lib/transformer_block.py /serving/app/lib
WORKDIR /serving/app
RUN apt-get update && apt-get install -y python-venv

RUN python3 -m venv venv && source venv/bin/activate && pip install --upgrade --no-cache-dir -r gpu_base_requirements && pip install --no-cache-dir keras==3.0.0
CMD ["source venv/bin/activate", "python", "app.py"]
