FROM tensorflow/tensorflow:2.15.0-gpu

USER root
RUN mkdir /serving
ADD app  /serving 
RUN mkdir /serving/app/bin
ADD  ../src/gpt/bin/gpt-books.keras /serving/app/bin
WORKDIR /serving/app
RUN apt update

RUN pip install --upgrade --no-cache-dir -r requirements && pip install --no-cache-dir keras==3.0.0
